export const pricing = [
  {
    id: "basic",
    titleKey: "pricing.basic.title",
    price: "$1,500",
    descriptionKey: "pricing.basic.description",
    featuresKeys: [
      "pricing.basic.features.design",
      "pricing.basic.features.implementation",
      "pricing.basic.features.support",
      "pricing.basic.features.documentation",
      "pricing.basic.features.revisions",
    ],
    highlighted: false,
  },
  {
    id: "professional",
    titleKey: "pricing.professional.title",
    price: "$3,500",
    descriptionKey: "pricing.professional.description",
    featuresKeys: [
      "pricing.professional.features.design",
      "pricing.professional.features.implementation",
      "pricing.professional.features.support",
      "pricing.professional.features.documentation",
      "pricing.professional.features.revisions",
      "pricing.professional.features.optimization",
      "pricing.professional.features.training",
    ],
    highlighted: true,
  },
  {
    id: "enterprise",
    titleKey: "pricing.enterprise.title",
    price: "$8,000+",
    descriptionKey: "pricing.enterprise.description",
    featuresKeys: [
      "pricing.enterprise.features.design",
      "pricing.enterprise.features.implementation",
      "pricing.enterprise.features.support",
      "pricing.enterprise.features.documentation",
      "pricing.enterprise.features.revisions",
      "pricing.enterprise.features.optimization",
      "pricing.enterprise.features.training",
      "pricing.enterprise.features.contact",
      "pricing.enterprise.features.integrations",
    ],
    highlighted: false,
  },
]
