export const projects = [
  {
    id: 1,
    titleKey: "projects.aiContentGenerator.title",
    descriptionKey: "projects.aiContentGenerator.description",
    image: "/placeholder.svg?height=400&width=600",
    tags: ["Full-Stack", "Business"],
    link: "#",
    fullDescriptionKey: "projects.aiContentGenerator.fullDescription",
  },
  {
    id: 2,
    titleKey: "projects.virtualAssistant.title",
    descriptionKey: "projects.virtualAssistant.description",
    image: "/placeholder.svg?height=400&width=600",
    tags: ["Forums", "Gameserver", "XenForo"],
    link: "#",
    fullDescriptionKey: "projects.virtualAssistant.fullDescription",
  },
  {
    id: 3,
    titleKey: "projects.predictiveAnalytics.title",
    descriptionKey: "projects.predictiveAnalytics.description",
    image: "/placeholder.svg?height=400&width=600",
    tags: ["Forums", "Gameserver", "XenForo"],
    link: "#",
    fullDescriptionKey: "projects.predictiveAnalytics.fullDescription",
  },
  {
    id: 4,
    titleKey: "projects.documentProcessor.title",
    descriptionKey: "projects.documentProcessor.description",
    image: "/placeholder.svg?height=400&width=600",
    tags: ["Portal", "Gameserver"],
    link: "#",
    fullDescriptionKey: "projects.documentProcessor.fullDescription",
  },
  {
    id: 5,
    titleKey: "projects.sentimentAnalysis.title",
    descriptionKey: "projects.sentimentAnalysis.description",
    image: "/placeholder.svg?height=400&width=600",
    tags: ["Webstore", "Gameserver", "Tebex"],
    link: "#",
    fullDescriptionKey: "projects.sentimentAnalysis.fullDescription",
  },
  {
    id: 6,
    titleKey: "projects.recommendationEngine.title",
    descriptionKey: "projects.recommendationEngine.description",
    image: "/placeholder.svg?height=400&width=600",
    tags: ["Forums", "Business", "XenForo"],
    link: "#",
    fullDescriptionKey: "projects.recommendationEngine.fullDescription",
  },
]
