export const projects = [
  {
    id: 1,
    titleKey: "projects.aiContentGenerator.title",
    descriptionKey: "projects.aiContentGenerator.description",
    image: "/placeholder.svg?height=400&width=600",
    tags: ["Next.js", "OpenAI", "TailwindCSS"],
    link: "#",
    fullDescriptionKey: "projects.aiContentGenerator.fullDescription",
  },
  {
    id: 2,
    titleKey: "projects.virtualAssistant.title",
    descriptionKey: "projects.virtualAssistant.description",
    image: "/placeholder.svg?height=400&width=600",
    tags: ["React", "Node.js", "MongoDB"],
    link: "#",
    fullDescriptionKey: "projects.virtualAssistant.fullDescription",
  },
  {
    id: 3,
    titleKey: "projects.predictiveAnalytics.title",
    descriptionKey: "projects.predictiveAnalytics.description",
    image: "/placeholder.svg?height=400&width=600",
    tags: ["Python", "TensorFlow", "D3.js"],
    link: "#",
    fullDescriptionKey: "projects.predictiveAnalytics.fullDescription",
  },
  {
    id: 4,
    titleKey: "projects.documentProcessor.title",
    descriptionKey: "projects.documentProcessor.description",
    image: "/placeholder.svg?height=400&width=600",
    tags: ["Computer Vision", "NLP", "AWS"],
    link: "#",
    fullDescriptionKey: "projects.documentProcessor.fullDescription",
  },
  {
    id: 5,
    titleKey: "projects.sentimentAnalysis.title",
    descriptionKey: "projects.sentimentAnalysis.description",
    image: "/placeholder.svg?height=400&width=600",
    tags: ["NLP", "React", "Python"],
    link: "#",
    fullDescriptionKey: "projects.sentimentAnalysis.fullDescription",
  },
  {
    id: 6,
    titleKey: "projects.recommendationEngine.title",
    descriptionKey: "projects.recommendationEngine.description",
    image: "/placeholder.svg?height=400&width=600",
    tags: ["Machine Learning", "GraphQL", "Redis"],
    link: "#",
    fullDescriptionKey: "projects.recommendationEngine.fullDescription",
  },
]
